# The name of our workflow
name: Android

on:
  pull_request:
      - master
      - develop
      - CI/android
  push:
    branches:
      - master
      - develop
      - CI/android
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
	with :
	  java-version: 11
      - name: Build the app
        run: mobile/gradlew build
